carolinehuguet/opoil

app/models/dog.rb, app/models/user.rb, app/models/walk.rb, db/migrate/20201116181131_remove_picture_from_users.rb, db/migrate/20201116181323_remove_picture_from_dogs.rb, db/schema.rb
J'ai modifié les validation de dogs et users
=> corrigé les models

config/routes.rb
Salut les amis,
Nous avons créé les routes pour notre app Opoil. Voir les routes attachées.
=> Created routes for Opoil

app/views/pages/home.html.erb
J'ai rajouté un h1 et un btn 'Trouver un chien'
=> implement h1 + btn

.gitignore, Gemfile, Gemfile.lock
Hello, je viens de lier le compte cloudinary à notre app :)
=> Opoil cloudinary

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb, app/views/shared/_cards.html.erb
J'ai crée un card simple pour l'instant. 
Je n'ai pas fini mais j'ai besoin du travail de Steven pour continuer 🐶
=> implement _card.html.erb

app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Hello les gens, j'ai créé une navbar (qui n'est pas encore super jojo) mais on a une base de travail et elle est reliée à chaque page :)
=> Create the navbar

app/views/dogs/index.html.erb, app/views/dogs/show.html.erb
Changed .photo to .picture and tested that it works (it does)
=> Fixed the photo links in the Dogs show and index

app/controllers/walks_controller.rb, app/views/walks/new.html.erb
Coucou ! 
Voici les nouveaux fichiers pour la page 'création de promenade' :)
Zoubi
=> Create a new walk

app/assets/stylesheets/components/_cards.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb, app/views/shared/_cards.html.erb, config/environments/development.rb, config/environments/production.rb
J'ai refait mes cards propre + page d'accueil
=> Home page ameliore

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Amélioration de la home (centrage des cards, ombres plus discrètes, typo, couleurs, background, padding)
=> Ameliorer la home

app/controllers/dashboards_controller.rb, app/views/dashboards/show.html.erb, config/locales/fr.yml, test/controllers/dashboard_controller_test.rb
Create a dashboard that shows the current user's dogs, walks and dog's walks
=> add the current_user's walks, dogs and dog walk's to the dashboard

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
J'ai mis le login + couleur de fond
=> finition de la navbar

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_show.scss, app/views/dogs/show.html.erb
J'ai ajouté des div pour organiser la page, une card pour le propriétaire et des boutons.
=> Fixed the layout of the show page

app/controllers/pages_controller.rb
Hello ! J'ai autorisé l'accès à la homepage, l'index et la show des dogs.
=> Authorized access to the homepage, the dog index and show

app/views/dogs/show.html.erb
Fixed the button to acces the new walk page.
Added new_dog_walk_path(@dog) to the path
=> Fixed the button to acces the new alk page

db/seeds.rb
J'ai ajouté deux seeds de promenades aux chiens de Steven
=> Add walk seeds for steven's profil

app/views/pages/home.html.erb
=> home change

app/controllers/walks_controller.rb, app/views/walks/new.html.erb
Hello ! On a résolu les problèmes du formulaires des balades avec Lomig !
=> Resolve walk form issues

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/pages/_home.scss, app/views/dashboards/show.html.erb, app/views/devise/sessions/new.html.erb, app/views/dogs/index.html.erb, app/views/dogs/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Améliorations css sur la home, éléments centrés sur chaque page, ajout d'une description sur la home, modifications des cards dans le dashboard :)
=> Amelioration de css

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_cards.scss, app/views/dashboards/show.html.erb, app/views/dogs/index.html.erb, app/views/dogs/show.html.erb
=> Amelioration de la show

db/migrate/20201119142102_change_description_to_be_text_in_dogs_and_users.rb, db/schema.rb
J'ai changé la :description de user et dog en :text
=> change string en text

app/views/dashboards/show.html.erb
Added an ugly edit button to the dog card in the dashboard.
Je vais modifier le style global de la card plus tard.
=> Added an ugly edit button to the dog card in the dashboard

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/pages/_show.scss, app/views/pages/home.html.erb
J'ai ajouté un hover sur les cards de la homepage !
=> add hover to cards

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_walk_request.scss, app/views/dashboards/show.html.erb
Hello ! j'ai amélioré le style de la promenade en attente de validation dans le dashboard. A faire évoluer en fonction de la couleur du fond du site.
=> improved new walk request in dashboard

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/dogs_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/javascript/plugins/init_mapbox.js, app/models/dog.rb, app/views/dogs/_form.html.erb, app/views/dogs/_info_window.html.erb, app/views/dogs/index.html.erb, config/initializers/geocoder.rb, db/migrate/20201119151854_add_coordinates_to_dogs.rb, db/schema.rb, db/seeds.rb, package.json, yarn.lock
J'ai crée une map
Rajouté 3 colonnes dans Dogs
Rajouté l'adresse dans le formulaire
Rajouté les seeds adresse des dogs
=> create map and add seeds address

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Ajout d'une background image pour la home, alignement des textes dans les cards de show
=> background image home and alignement text cards show

app/views/dogs/_info_window.html.erb
J'ai ajouté un lien dans les fenêtres des dogs dans la map pour acceder au détail du chien
=> link dog.name, dog

app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_colors.scss, app/views/shared/_navbar.html.erb
Couleur de fond des pages, avatar changé, autres
=> design ameliorations

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/dashboards/_dogs.html.erb
J'ai amélioré la carte chien dans le dashboard. N'hésitez pas à me dire si vous avez d'autres suggestions pour l'améliorer.
Merci :)
=> dog card in the dashboard

app/views/dashboards/_dogs.html.erb, app/views/dashboards/_mydogswalks.html.erb, app/views/dashboards/_walks.html.erb, app/views/dashboards/show.html.erb
Hello ! J'ai ajouté une navbar pour naviguer dans le dashboard entre les promenades, les chiens et les promenades des chiens de l'utilisateur.
=> Create a tab nav for walks, dogs and dog's walks in dashboard

app/views/dashboards/_walks.html.erb
Added walk status to the walk card.
=> Added walk status to the walk card

app/views/dashboards/show.html.erb
Les onglets ne s'affichent que s'ils ont du contenu.
=> don't show tabs when no content

app/views/dogs/index.html.erb
J'ai mis l'avatar plus haut et rajouté le prix
=> changement de cards dans l'index dog

app/assets/stylesheets/components/_cards.scss, app/views/dashboards/_mydogswalks.html.erb
Dashboard card dog's walks style.
=> improved dog's walks cards style in dashboard

app/assets/stylesheets/pages/_dashboard.scss, app/views/dashboards/_dogs.html.erb
Improved the dog card in the dashboard.
=> Improved the dog card in the dashboard

app/views/pages/home.html.erb
J'ai changé dans la card "propriétaire:" par "Toutou de"
=> changé propriétaire par toutou de

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_show.scss, app/views/dogs/new.html.erb, app/views/shared/_navbar.html.erb, app/views/walks/new.html.erb
Lien qui se surlignent quand on est sur une page, walk new améliorée
=> Change new walk and navbar links

app/views/dogs/show.html.erb
J'ai ajouté une condition pour ne pas montrer le bouton de booking dans la show si current_user == @dog.owner
=> Owner of dog can't schedule a walk with them.

app/views/shared/_navbar.html.erb
=> Signed in user sees their avatar in the navbar.

app/views/dogs/_info_window.html.erb
J'ai rajouté un photo dans la map
=> add picture info_windows

app/assets/stylesheets/application.scss, app/views/dashboards/_mydogswalks.html.erb, app/views/dashboards/_walks.html.erb
=> color for walks

app/assets/stylesheets/components/_badge.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/dashboards/_mydogswalks.html.erb, app/views/dashboards/_walks.html.erb
Improved card's style for dog's walks in dashboard
=> improve the dog's walks card's style in dashboard

app/assets/stylesheets/components/_cards.scss, app/views/dashboards/_mydogswalks.html.erb, app/views/dashboards/_walks.html.erb
Improve the style of walks cards in dashboard.
=> improve the card's style for walks in dashboard
